#!/bin/bash

SERVICE_FIVEF="http://localhost:55111"
SERVICE_LLAMA="http://localhost:11434"

LLM_MODEL="gemma3:4b"

PROMPT_SUMMARY="Summarize in 2 sentences. Do not repeat this instruction, directly give the answer. Focus on the most important, surprising or shocking aspects. Do not state the obvious."
PROMPT_KEYPOINTS="Extract the most important facts and information from the text in max 5 bullet points, each as a separate list item. Do not repeat this instruction, directly give the answer. Keep it as short as possible."


curl --no-progress-meter --fail "$SERVICE_FIVEF/makefulltextfeed.php?url=sec%3A%2F%2Fwww.tagesschau.de%2Findex~rss2.xml&max=1&links=preserve" > /dev/null

llama() {
    curl "$SERVICE_LLAMA/api/chat" -d "{
    \"model\": \"$LLM_MODEL\",
    \"messages\": [
        {
        \"role\": \"user\",
        \"content\": \"$2\n\n$1\"
        }
    ],
    \"stream\": false
    }" | jq -r .message.content
}

curl -s "$1" -o feed.rss
output=$(date +"%Y-%m-%d")

{
    echo '<style>@font-face { font-family: Chomsky; src: url("chomsky/dist/Chomsky.otf") format("opentype"); } h1 { font-family: Chomsky; font-size: 400% } </style>'
    printf "\n\n# Timm's Daily Digest\n\n"
    printf "<center>%s</center>\n\n" "$output"
} > "$output.md"


echo "cat  //item/link/text()" | xmllint --shell feed.rss | grep -E '^\w' |
    while read -r url ; do
    	echo "$url"

        json=$(curl "$SERVICE_FIVEF/extract.php?url=$url")
        title=$(echo "$json" | jq -r .title)
        content=$(echo "$json" | jq -r .content | sed 's/"//g' | tr '\n' ' ')

        if [[ "$content" == "null" ]]; then
            echo "Content extraction failed: $url"
            continue
        fi

        {
            printf "## %s \n\n" "$title"
            printf "Source: <%s> \n\n" "$url"

            printf "%s \n\n" "$(llama "$PROMPT_SUMMARY" "$content")"
            printf "%s \n\n" "$(llama "$PROMPT_KEYPOINTS" "$content")"
        } >> "$output.md"
    done


rm feed.rss
